platform :ios, ‘7.0’
pod 'MJRefresh', '~> 3.1.0'
pod 'SDAutoLayout', '~> 1.53'
pod 'AFNetworking', '~> 3.1.0'
pod 'YYWebImage', '~> 1.0.3'
pod 'YYModel', '~> 1.0.3'
pod 'YTKKeyValueStore', '~> 0.1.2'
pod 'UMengAnalytics-NO-IDFA'
pod 'Firebase/Core'
pod 'Firebase/AdMob'

